name: Release

on:
  push:
    tags:
      - "v*" # Trigger on version tags

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for creating releases
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      # Install pnpm using npm first
      - name: Install pnpm
        run: npm install -g pnpm@8.15.1

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Prepare release
        run: pnpm run prepare-release

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Zip the proto directory
          cd release && zip -r proto.zip proto/

          # Get version from tag
          VERSION=${GITHUB_REF#refs/tags/}

          # Create release with files
          gh release create $VERSION \
            --title "Release $VERSION" \
            --notes "Release $VERSION" \
            p2p-node.js \
            proto.zip \
            checksums.txt
